"""
YATRA 2026 - Batch QR Processor
===============================
Extracts successful registrations from XLSX, generates QR codes,
and uploads to Supabase database for ticket email dispatch.

Usage:
    python batch_qr_processor.py                  # Dry run (preview)
    python batch_qr_processor.py --commit         # Actually insert into database
    python batch_qr_processor.py --help           # Show help
"""

import os
import sys
import uuid
import random
import string
import base64
import argparse
from io import BytesIO
from datetime import datetime
from typing import List, Dict, Any, Optional

import pandas as pd
from dotenv import load_dotenv

# Load environment variables
load_dotenv()

# Configuration
INPUT_FILE = "YATRA REG LINK -26.xlsx"
STATUS_COLUMN = "Order Status"
SUCCESS_VALUES = ["Success", "Paid", "Transaction Successful"]  # Case-insensitive

# Column mappings (XLSX column name -> internal name)
COLUMN_MAP = {
    "Tracking": "tracking_id",
    "Order": "order_id", 
    "Billing Email": "email",
    "Student Name": "name",  # Use Student Name instead of Billing Name
    "College Name": "college",
    "Billing Tel": "phone",  # Use Billing Tel instead of Phone
    "Amount": "amount",
}


def generate_6_digit_code() -> str:
    """Generate a unique 6-digit alphanumeric code."""
    return ''.join(random.choices(string.ascii_uppercase + string.digits, k=6))


def generate_qr_code_base64(payload: str) -> str:
    """Generate QR code as base64-encoded PNG."""
    try:
        import qrcode
        qr = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_L,
            box_size=10,
            border=4,
        )
        qr.add_data(payload)
        qr.make(fit=True)
        
        img = qr.make_image(fill_color="black", back_color="white")
        buffer = BytesIO()
        img.save(buffer, format="PNG")
        return base64.b64encode(buffer.getvalue()).decode('utf-8')
    except ImportError:
        print("Warning: qrcode package not installed. QR codes will be generated by edge function.")
        return ""


def extract_records_from_xlsx(file_path: str) -> List[Dict[str, Any]]:
    """Extract successful registration records from XLSX file."""
    print(f"\n{'='*60}")
    print(f"Reading: {file_path}")
    print(f"{'='*60}")
    
    df = pd.read_excel(file_path)
    print(f"Total rows in file: {len(df)}")
    
    # Show available columns
    print(f"\nAvailable columns ({len(df.columns)}):")
    for i, col in enumerate(df.columns[:15]):
        print(f"  {i}: {col}")
    if len(df.columns) > 15:
        print(f"  ... and {len(df.columns) - 15} more")
    
    # Check for required columns
    missing_cols = []
    for xlsx_col in COLUMN_MAP.keys():
        if xlsx_col not in df.columns:
            # Try case-insensitive match
            matched = [c for c in df.columns if c.lower().strip() == xlsx_col.lower().strip()]
            if not matched:
                missing_cols.append(xlsx_col)
    
    if missing_cols:
        print(f"\nWarning: Missing columns: {missing_cols}")
    
    # Filter for successful transactions (case-insensitive)
    if STATUS_COLUMN not in df.columns:
        print(f"Error: Status column '{STATUS_COLUMN}' not found!")
        sys.exit(1)
    
    df[STATUS_COLUMN] = df[STATUS_COLUMN].astype(str).str.strip()
    success_mask = df[STATUS_COLUMN].str.lower().isin([s.lower() for s in SUCCESS_VALUES])
    successful_df = df[success_mask]
    
    print(f"\nFiltering by status column: '{STATUS_COLUMN}'")
    print(f"Success values: {SUCCESS_VALUES}")
    print(f"Successful transactions: {len(successful_df)}")
    
    # Show status distribution
    print(f"\nStatus distribution:")
    for status, count in df[STATUS_COLUMN].value_counts().items():
        marker = " <-- selected" if str(status).strip().lower() in [s.lower() for s in SUCCESS_VALUES] else ""
        print(f"  {status}: {count}{marker}")
    
    # Extract records
    records = []
    for idx, row in successful_df.iterrows():
        record = {"row_index": idx}
        
        for xlsx_col, internal_name in COLUMN_MAP.items():
            # Handle column name variations
            value = None
            if xlsx_col in df.columns:
                value = row[xlsx_col]
            else:
                # Try case-insensitive match
                for col in df.columns:
                    if col.lower().strip() == xlsx_col.lower().strip():
                        value = row[col]
                        break
            
            # Clean value
            if pd.isna(value):
                value = None
            elif isinstance(value, str):
                value = value.strip()
            
            record[internal_name] = value
        
        # Skip records without email
        if not record.get("email"):
            continue
        
        # Normalize email
        record["email"] = str(record["email"]).lower().strip()
        
        # Use tracking_id as unique identifier
        if not record.get("tracking_id"):
            record["tracking_id"] = f"YATRA-{uuid.uuid4().hex[:8].upper()}"
        else:
            record["tracking_id"] = str(record["tracking_id"]).strip()
        
        records.append(record)
    
    print(f"\nValid records extracted: {len(records)}")
    return records


def check_existing_in_supabase(supabase, tracking_ids: List[str]) -> Dict[str, Any]:
    """Check which tracking IDs already exist in database."""
    existing = {}
    
    # Check in batches to avoid query limits
    batch_size = 50
    for i in range(0, len(tracking_ids), batch_size):
        batch = tracking_ids[i:i + batch_size]
        
        result = supabase.table("registrations") \
            .select("id, email, payment_utr, payment_status, ticket_email_sent") \
            .in_("payment_utr", batch) \
            .execute()
        
        for row in result.data:
            existing[row.get("payment_utr")] = row
    
    return existing


def process_records(
    records: List[Dict[str, Any]], 
    dry_run: bool = True,
    supabase = None
) -> Dict[str, Any]:
    """Process records: generate codes, QR, and optionally upload to Supabase."""
    
    results = {
        "total": len(records),
        "new": 0,
        "skipped_existing": 0,
        "skipped_already_paid": 0,
        "updated": 0,
        "errors": [],
        "preview": []
    }
    
    if not dry_run and supabase is None:
        raise ValueError("Supabase client required when not in dry-run mode")
    
    # Check existing records
    existing_map = {}
    if not dry_run:
        tracking_ids = [r["tracking_id"] for r in records if r.get("tracking_id")]
        existing_map = check_existing_in_supabase(supabase, tracking_ids)
        print(f"\nExisting records in database: {len(existing_map)}")
    
    print(f"\n{'='*60}")
    print(f"Processing {len(records)} records... (dry_run={dry_run})")
    print(f"{'='*60}")
    
    for i, record in enumerate(records):
        tracking_id = record.get("tracking_id")
        email = record.get("email")
        
        # Check if already exists
        existing = existing_map.get(tracking_id)
        if existing:
            if existing.get("payment_status") == "paid" and existing.get("ticket_email_sent"):
                results["skipped_already_paid"] += 1
                continue
            elif existing.get("payment_status") == "paid":
                results["skipped_existing"] += 1
                continue
        
        # Generate 6-digit code
        code_6_digit = generate_6_digit_code()
        
        # Generate QR payload
        qr_payload = f"YATRA2026:{code_6_digit}:{tracking_id}"
        
        # Generate QR code (optional, edge function will generate if needed)
        qr_base64 = generate_qr_code_base64(qr_payload) if not dry_run else ""
        
        # Prepare registration data
        reg_data = {
            "name": record.get("name") or "Unknown",
            "email": email,
            "phone": record.get("phone"),
            "college": record.get("college") or "Unknown",
            "payment_status": "paid",
            "payment_utr": tracking_id,
            "payment_confirmed_at": datetime.utcnow().isoformat(),
            "ticket_email_sent": False,
            "ticket_generated": False,
        }
        
        # Preview info
        preview_item = {
            "email": email,
            "name": record.get("name"),
            "tracking_id": tracking_id,
            "code_6_digit": code_6_digit,
            "action": "INSERT"
        }
        
        if dry_run:
            results["preview"].append(preview_item)
            results["new"] += 1
        else:
            try:
                # Insert into registrations table
                insert_result = supabase.table("registrations").insert(reg_data).execute()
                
                if insert_result.data:
                    results["new"] += 1
                    if (i + 1) % 10 == 0:
                        print(f"  Processed {i + 1}/{len(records)}...")
                else:
                    results["errors"].append({
                        "tracking_id": tracking_id,
                        "reason": "Insert returned no data"
                    })
            except Exception as e:
                results["errors"].append({
                    "tracking_id": tracking_id,
                    "reason": str(e)
                })
    
    return results


def print_results(results: Dict[str, Any], dry_run: bool):
    """Print processing results."""
    print(f"\n{'='*60}")
    print(f"RESULTS {'(DRY RUN - No changes made)' if dry_run else '(COMMITTED)'}")
    print(f"{'='*60}")
    
    print(f"\n  Total records:        {results['total']}")
    print(f"  New insertions:       {results['new']}")
    print(f"  Skipped (paid+sent):  {results['skipped_already_paid']}")
    print(f"  Skipped (paid only):  {results['skipped_existing']}")
    print(f"  Updated:              {results['updated']}")
    print(f"  Errors:               {len(results['errors'])}")
    
    if results.get("errors"):
        print(f"\n  Errors:")
        for err in results["errors"][:5]:
            print(f"    - {err['tracking_id']}: {err['reason']}")
        if len(results["errors"]) > 5:
            print(f"    ... and {len(results['errors']) - 5} more")
    
    if dry_run and results.get("preview"):
        print(f"\n  Preview (first 10 records):")
        print(f"  {'Email':<40} {'Name':<25} {'Code'}")
        print(f"  {'-'*40} {'-'*25} {'-'*6}")
        for item in results["preview"][:10]:
            email = (item['email'][:37] + '...') if len(item['email']) > 40 else item['email']
            name = (item['name'][:22] + '...') if item['name'] and len(item['name']) > 25 else (item['name'] or 'N/A')
            print(f"  {email:<40} {name:<25} {item['code_6_digit']}")
        
        if len(results["preview"]) > 10:
            print(f"  ... and {len(results['preview']) - 10} more")


def main():
    parser = argparse.ArgumentParser(
        description="YATRA 2026 - Batch QR Processor",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    python batch_qr_processor.py                  # Preview (dry run)
    python batch_qr_processor.py --commit         # Insert into database
    python batch_qr_processor.py -i custom.xlsx   # Use custom input file
        """
    )
    parser.add_argument(
        "-i", "--input", 
        default=INPUT_FILE,
        help=f"Input XLSX file (default: {INPUT_FILE})"
    )
    parser.add_argument(
        "--commit", 
        action="store_true",
        help="Actually commit changes to database (default: dry run)"
    )
    parser.add_argument(
        "--limit",
        type=int,
        default=None,
        help="Limit number of records to process"
    )
    
    args = parser.parse_args()
    dry_run = not args.commit
    
    print(f"\n{'#'*60}")
    print(f"#  YATRA 2026 - Batch QR Processor")
    print(f"#  Mode: {'DRY RUN (preview only)' if dry_run else 'COMMIT (writing to database)'}")
    print(f"#  Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"{'#'*60}")
    
    # Extract records from XLSX
    records = extract_records_from_xlsx(args.input)
    
    if not records:
        print("\nNo valid records found. Exiting.")
        sys.exit(0)
    
    # Apply limit if specified
    if args.limit:
        records = records[:args.limit]
        print(f"\nLimited to first {args.limit} records")
    
    # Initialize Supabase client if committing
    supabase = None
    if not dry_run:
        try:
            from supabase import create_client, Client
            
            url = os.getenv("SUPABASE_URL") or os.getenv("VITE_SUPABASE_URL") or os.getenv("NEXT_PUBLIC_SUPABASE_URL")
            key = os.getenv("SUPABASE_SERVICE_KEY") or os.getenv("SUPABASE_SERVICE_ROLE_KEY") or os.getenv("SUPABASE_KEY")
            
            if not url or not key:
                print("\nError: SUPABASE_URL and SUPABASE_SERVICE_KEY must be set in .env")
                print("Add these to your .env file:")
                print("  SUPABASE_URL=https://mnboyuyajxghqbbkdqhi.supabase.co")
                print("  SUPABASE_SERVICE_KEY=<your-service-role-key>")
                sys.exit(1)
            
            supabase: Client = create_client(url, key)
            print(f"\nConnected to Supabase: {url}")
            
        except ImportError:
            print("\nError: supabase-py package not installed.")
            print("Install with: pip install supabase")
            sys.exit(1)
    
    # Process records
    results = process_records(records, dry_run=dry_run, supabase=supabase)
    
    # Print results
    print_results(results, dry_run)
    
    # Next steps
    if dry_run:
        print(f"\n{'='*60}")
        print("NEXT STEPS:")
        print(f"{'='*60}")
        print("1. Review the preview above")
        print("2. If everything looks correct, run with --commit:")
        print(f"   python batch_qr_processor.py --commit")
        print("3. After import, go to Admin Panel and click 'Send tickets'")
    else:
        print(f"\n{'='*60}")
        print("IMPORT COMPLETE!")
        print(f"{'='*60}")
        print("Next: Go to Admin Panel → Preview recipients → Send tickets")
    
    print(f"\nDone! {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")


if __name__ == "__main__":
    main()
